### ISSUE TITLE
RStudio “cheatsheets” in section 6.5 redirects to "Page Not Found"

### ISSUE THREAD

**Issue by sidpssp** [daviddalpiaz/appliedstats#106]
If you click on the hyperlink RStudio “cheatsheets”in section 6.5, it redirects to an old page which is not present anymore.

The old page URL is:
https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf

However, Rstudio seems to have updated this cheatsheet to a new URL, which is as follows:
https://www.rstudio.com/wp-content/uploads/2019/01/Cheatsheets_2019.pdf

This can be easily updated in the **r-resources.Rmd** file.

**Comment by mrwork01** [comment]
Fixed on Pull Request #108
