### ISSUE TITLE
What should be done for "TODO: coercion" in chapter3

### ISSUE THREAD

**Issue by chadyuu** [daviddalpiaz/appliedstats#129]
`TODO: coercion` seems to be left unresolved.
https://github.com/daviddalpiaz/appliedstats/blob/53b7a49e71120ddb86aab23290ab5cbd2c1919f8/data-and-programming.Rmd#L210

However, I think there is an explanation for coercion as follows.
https://github.com/daviddalpiaz/appliedstats/blob/53b7a49e71120ddb86aab23290ab5cbd2c1919f8/data-and-programming.Rmd#L212-L217

Should we delete the TODO line or fix something more?

**Comment by daviddalpiaz** [comment]
Hmmm. Good catch. I think that explanation is sufficient for the local purposes of this text, but perhaps we should add a footnote to a reference about the details of type coercion in R. Maybe a link to a relevant section of Advanced R? https://adv-r.hadley.nz/

**Comment by chadyuu** [comment]
I have just created a pull request. Please confirm this update reflects your intention.
