### ISSUE TITLE
Broken Link to ISL in logistic.Rmd

### ISSUE THREAD

**Issue by sfindley899** [daviddalpiaz/appliedstats#152]
The link to ISR in `logistic.Rmd` appears to be broken.

Was it supposed to direct to the Introduction to Statistical Learning book by James, Witten, Hastie, Tibshirani, and Taylor?

It seems that the authors have a dedicated website for the book:  https://www.statlearning.com/

The book is also available on Springer here: https://link.springer.com/book/10.1007/978-3-031-38747-0.

**Comment by daviddalpiaz** [comment]
Fixed. Thanks. Change should be live shortly.
