### ISSUE TITLE
Chaptering, Sectioning

### ISSUE THREAD

**Issue by daviddalpiaz** [daviddalpiaz/appliedstats#28]
Create smaller chapters.
Group into sections.

**Comment by coatless** [comment]
FYI Sections are:

`# (PART) Section Name {-}`

You may want to consider moving large code chunks to an appendix:

``` md
# (APPENDIX) Appendix {-}
# Appendix A
## Simulation
```

**Comment by daviddalpiaz** [comment]
This has mostly been completed. Chapters are close to finalized.

**Comment by coatless** [comment]
@daviddalpiaz should we save a copy of this under @uiucstats org?
