### ISSUE TITLE
Correct a typo

### ISSUE THREAD

**Issue by tonymazn** [daviddalpiaz/appliedstats#79]
On 8.7 "We modify our notation slightly to make it clear that **the the** predicted value is a function of", there is double words "the", I tested on IE and Chrome, both displayed double "the".

**Comment by coatless** [comment]
@tonymazn thanks! Is there anyway you could fix it via a PR? 

To modify it on GitHub press the "edit" button.

<img width="1014" alt="Screen Shot 2019-05-31 at 8 30 32 PM" src="https://user-images.githubusercontent.com/833642/58741796-0f5bcc80-83e3-11e9-870a-332d165ef0bb.png">

Then find the typo:

<img width="758" alt="Screen Shot 2019-05-31 at 8 34 01 PM" src="https://user-images.githubusercontent.com/833642/58741830-9f9a1180-83e3-11e9-83be-d6c5472b74d0.png">


From there:

1. Fix the typo.
2. Describe what changed
3. Select create a new branch for this commit and start a pull request (PR)
4. Then press the green commit button.

**Comment by tonymazn** [comment]
Hi coatless,

I commented a change couple minutes ago..

Thank you
Tony

**Comment by coatless** [comment]
@tonymazn awesome thanks! @daviddalpiaz will merge in #80 shortly. 

Feel free to follow the above advice if you find more typos! 

Thanks again!
