### ISSUE TITLE
Switch over to GH Actions runner

### ISSUE THREAD

**Issue by coatless** [daviddalpiaz/appliedstats#99]
Some steps to be taken:

1. Disabling `.travis.yaml` by deleting it
2. Remove `deployment/` folder
3. Add `.github/workflows/bookdown.yaml`

Notes:

- We'll use a slightly modified `bookdown` action to avoid reliance on Netlify. 
- The main website will remain "active", but until the runner builds will _not_ automatically update. 
- It may be advantageous in non-peak hours to rebuild the `gh-pages` branch as it contains old artifacts.

**Comment by coatless** [comment]
Disabled `.travis.yaml` in: 60f8eb1055495f6c60f58f4725fe7f4ede556587

Added GitHub action in: 28681957321d54b0ebdb054aaec342c025442e56

Moving to test deployments in a PR structure since the runner should now be picked up in the PR.

**Comment by coatless** [comment]
Okay, we didn't use a branch... Few commit notes:

Switched from install `pandoc` with brew to using the `r-lib/actions` recipe: 308f2eb9b8d7dce515759db1d9e0232529ae4e0c

Next, we battled to add `xquartz` to enable `{plot3D}` r package by using `brew install xquartz --cask` in:

233794b45dc54117ee02b78f1347334fcd4aab3a and f329cb258ddc75482f52ba57993eff89cf0e5aaf

Note, we now have a working textbook!

**Comment by coatless** [comment]
Lastly, we're using the `main`/`master` instead of keyed versions of the installation recipes. So, if any of these stages fail, we'll probably either need to wait or key to the latest versions. (I'm going the `main` route since R 4.1 was just released last week.)

https://github.com/daviddalpiaz/appliedstats/blob/f329cb258ddc75482f52ba57993eff89cf0e5aaf/.github/workflows/bookdown.yaml#L18-L26

**Comment by daviddalpiaz** [comment]
Perfect, thanks! Gonna give it a quick test in a second.

**Comment by daviddalpiaz** [comment]
Wow. Works flawlessly. Now I'll have to go try the migration on some other repos by myself.
